### ISSUE TITLE
Publish js packages on NPM

### ISSUE THREAD

**Issue by arroyo** [Erdiko/user-admin#26]
What is involved?  Can we publish now?

note from Andy: 

- created base package: https://www.npmjs.com/package/erdiko-user-admin
- need to update the README
- need to test this package installation
- need to test 3rd party package inclusion
- need a way to 'add' and include 3rd party packages
- need to be able to include our own user-admin as a package in an app

Formerly ER-138: Publish js packages on NPM on Trello

**Comment by arroyo** [comment]
user edit still needs to be moved and unit tests updated/fixed

**Comment by saarmstrong** [comment]
* Flash Message Service from module
    * Figure out how/why the message service isn’t exposed like user service the importing application
    * can communicate via user service, but the message service may not be compatible
    * may have to use an event emitter

**Comment by saarmstrong** [comment]
Remaining Tasks
- Fix service exposing so the parent module uses the UsersService and MessageService from the NPM pkg consistently
- Refactor the components to pull out the HTML into a sep file from the TS file
- Look into providing UserResolve from the module

**Comment by saarmstrong** [comment]
I was able to expose the User and Message services as expected from this module for use in the parent as well as split the HTML templates into a separate file.

Due to some difficulty with the typescript/bundling process linking to an HTML asset became *quite* a pain. After a lot of research it seems this is a common problem when exporting components in a stand alone library. I tried using a rollup plugin to 'inline' the `templateUrl` with no luck as well as any attempts to use module namespacing with `module.id`.

I eventually just opted into creating a typescript module that just exported a single var named `tpl` that would compile and export as we expect. Also we use the rollup plugin to minify the HTML in the `tpl` var.

I was unable to pull out UserResolve (which is used for the `user/:id` route) since I could not cleanly pull out the existing routing without everything breaking all at once. I will create a new issue to see if we can expose the "fun" routes via our npm pkg.
