### ISSUE TITLE
Revised wires for user admin

### ISSUE THREAD

**Issue by arroyo** [Erdiko/user-admin#51]
follow up to #24 

Create another iteration of the wires.  Show empty and filled states for each component.  Think real-world examples of the same components.

**Comment by saarmstrong** [comment]
[ER-134.pdf](https://github.com/Erdiko/user-admin/files/957148/ER-134.pdf)

attached updated wires

**Comment by saarmstrong** [comment]
(requested updates per meeting)

**Comment by saarmstrong** [comment]
[ER-134_v2.pdf](https://github.com/Erdiko/user-admin/files/962806/ER-134_v2.pdf)

Updated Wireframes:
* Removed Radio Buttons from Video Elements. We will rely on URL parsing to determine the video source for VideoJS.
* Added "Delete" icons for elements.
* Removed Placeholder Video Thumbnail since we plan on using tiny video player.

**Comment by saarmstrong** [comment]
[ER-134_v3.pdf](https://github.com/Erdiko/user-admin/files/975206/ER-134_v3.pdf)

**Comment by saarmstrong** [comment]
[ER-134_v4.pdf](https://github.com/Erdiko/user-admin/files/977758/ER-134_v4.pdf)

updated wires
